server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # http://localhost:64412  # forwarding (http://localhost:8000/user -> http://localhost:64412)
          predicates:
            - Path=/user/**  # ?? gateway server? /user/**? ???? ??? user-service? ??
#            - Cookie=valid, user
          filters:
            - CustomAuthFilter
#            - AddRequestHeader=token, 1234
#            - RewritePath=/user/?(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://ORDER-SERVICE  # http://localhost:54412  # forwarding (http://localhost:8000/order -> http://localhost:54412)
          predicates:
            - Path=/order/**
#            - Method
          filters:
#            - RewritePath=/order/?(?<segment>.*), /$\{segment}

#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true