server:
  port: 8761  # Eureka server default port

spring:
  application:
    name: discovery-service  # ?? ???? applcation.name?? ?? !!

eureka:
  client:
    register-with-eureka: false  # client ?? false
    fetch-registry: false        # ??? discovery? ???? ??? false
  server:
    enableSelfPreservation: true  # ???? ???? ??? ?? ??? ?? ?? ?? ?? ?? ??